export const ADD_TODO_LIST = "ADD_TODO_LIST";
export const DELETE_TODO_LIST = "DELETE_TODO_LIST";
export const SUCCESS_TODO_LIST = 'SUCCESS_TODO_LIST';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';